name: Workflow for Codecov example-python
on: [push, pull_request]
jobs:
  run:
    strategy:
      matrix:
        label-version: [1,2,3,4,5,6,7,8,9,10]
        attempt: [1,2,3,4,5,6,7,8,9,10]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov app
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@d1f1eb8ced025a661e3a2070d7c9462978291164
        with:
          name: ${{ matrix.label-version }}-${{ matrix.attempt }}
          flags: smart-tests
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
